// City data for Reinigung pages.
// Includes real Stadtteile, label, demographic flavor and Wertstoffhof reference
// where useful. Stadtteile lists are kept honest (well-known districts only,
// no invented neighborhoods).

export const CITIES = {
  'achern': {
    label: 'Achern',
    lat: 48.6304, lng: 8.0717,
    plz: '77855',
    districts: ['Innenstadt','Önsbach','Mösbach','Fautenbach','Gamshurst','Sasbachried','Wagshurst','Oberachern','Großweier','Sasbachwalden'],
    umland: 'Sasbach, Kappelrodeck, Renchen, Bühl und das gesamte Umland im Ortenaukreis',
    wertstoffhof: 'Wertstoffhof Achern in der Industriestraße',
    flavor: 'im Ortenaukreis am Übergang vom Oberrhein in den Schwarzwald',
  },
  'baden-baden': {
    label: 'Baden-Baden',
    lat: 48.7610, lng: 8.2396,
    plz: '76530',
    districts: ['Innenstadt','Lichtental','Geroldsau','Ebersteinburg','Steinbach','Sandweier','Oos','Haueneberstein','Neuweier','Varnhalt'],
    umland: 'Sinzheim, Bühl, Gernsbach, Forbach und der gesamte Bäderdreieck-Raum',
    wertstoffhof: 'Wertstoffhof Steinbach (Industriegebiet) der Stadtreinigung Baden-Baden',
    flavor: 'mit historischen Villen, Bäderhotellerie und gehobenen Wohnlagen',
  },
  'buehl': {
    label: 'Bühl',
    lat: 48.6960, lng: 8.1318,
    plz: '77815',
    districts: ['Innenstadt','Altschweier','Eisental','Kappelwindeck','Moos','Neusatz','Oberbruch','Vimbuch','Weitenung','Balzhofen'],
    umland: 'Bühlertal, Ottersweier, Sinzheim, Achern und der Bühlertaler Raum',
    wertstoffhof: 'Wertstoffhof Bühl (Industriestraße)',
    flavor: 'in der Mittelbadischen Rheinebene mit landwirtschaftlich geprägtem Umland',
  },
  'ettlingen': {
    label: 'Ettlingen',
    lat: 48.9408, lng: 8.4072,
    plz: '76275',
    districts: ['Innenstadt','Bruchhausen','Ettlingenweier','Oberweier','Schluttenbach','Schöllbronn','Spessart'],
    umland: 'Karlsruhe, Rheinstetten, Karlsbad, Waldbronn und das südliche Hardtland',
    wertstoffhof: 'Wertstoffhof Ettlingen (Industriegebiet West)',
    flavor: 'südlich von Karlsruhe am Rand des Albtals',
  },
  'gaggenau': {
    label: 'Gaggenau',
    lat: 48.8024, lng: 8.3265,
    plz: '76571',
    districts: ['Innenstadt','Bad Rotenfels','Hörden','Michelbach','Ottenau','Selbach','Sulzbach','Mittelberg','Oberweier','Freiolsheim'],
    umland: 'Gernsbach, Kuppenheim, Rastatt, Bischweier und das mittlere Murgtal',
    wertstoffhof: 'Wertstoffhof Gaggenau (Bahnhofstraße)',
    flavor: 'im Murgtal mit vielen industriellen und gemischt genutzten Gebäuden',
  },
  'gernsbach': {
    label: 'Gernsbach',
    lat: 48.7616, lng: 8.3286,
    plz: '76593',
    districts: ['Innenstadt','Hilpertsau','Lautenbach','Obertsrot','Reichental','Scheuern','Staufenberg'],
    umland: 'Gaggenau, Forbach, Bad Herrenalb und das mittlere Murgtal',
    wertstoffhof: 'Wertstoffhof Scheuern (Stadtteil)',
    flavor: 'im oberen Murgtal mit Fachwerkbauten und schmalen Altstadtgassen',
  },
  'karlsruhe': {
    label: 'Karlsruhe',
    lat: 49.0069, lng: 8.4037,
    plz: '76131',
    districts: ['Innenstadt-Ost','Innenstadt-West','Durlach','Mühlburg','Oststadt','Weststadt','Knielingen','Daxlanden','Grünwinkel','Rüppurr','Waldstadt','Nordstadt','Südstadt','Hagsfeld','Neureut','Rintheim','Stupferich','Wolfartsweier','Hohenwettersbach','Beiertheim-Bulach','Weiherfeld-Dammerstock','Oberreut','Grötzingen','Palmbach'],
    umland: 'Ettlingen, Rheinstetten, Stutensee, Pfinztal, Weingarten, Karlsbad, Waldbronn und Eggenstein-Leopoldshafen',
    wertstoffhof: 'Wertstoffhöfe der Stadt Karlsruhe in der Maybachstraße sowie weitere Standorte (Daxlanden, Knielingen, Grötzingen)',
    flavor: 'mit Fächergrundriss, vielen Mehrfamilienhäusern und einem starken Mix aus Innenstadt-Wohnungen, Gewerbe und Gründerzeit-Altbauten',
  },
  'muggensturm': {
    label: 'Muggensturm',
    lat: 48.9001, lng: 8.3192,
    plz: '76461',
    districts: ['Ortskern','Industriegebiet'],
    umland: 'Rastatt, Bietigheim, Kuppenheim, Bischweier und der Raum Mittelbaden',
    wertstoffhof: 'Wertstoffhof Rastatt (zentrale Anlaufstelle für Muggensturm)',
    flavor: 'als kompakte Wohngemeinde mit Einfamilienhaus-Anteil und kleinem Gewerbegebiet',
  },
  'pforzheim': {
    label: 'Pforzheim',
    lat: 48.8922, lng: 8.6946,
    plz: '75175',
    districts: ['Innenstadt','Buckenberg','Dillweißenstein','Eutingen','Hohenwart','Würm','Brötzingen','Huchenfeld','Sonnenberg','Maihälden','Au','Hagenschieß'],
    umland: 'Niefern-Öschelbronn, Mühlacker, Birkenfeld, Neuenbürg und der nördliche Schwarzwaldrand',
    wertstoffhof: 'Wertstoffhof Pforzheim (Mannheimer Straße)',
    flavor: 'als Goldstadt mit gemischter Bebauung von Nachkriegs-Mehrfamilienhäusern bis zu Schwarzwaldhang-Lagen',
  },
  'rastatt': {
    label: 'Rastatt',
    lat: 48.8587, lng: 8.2057,
    plz: '76437',
    districts: ['Innenstadt','Niederbühl','Plittersdorf','Wintersdorf','Ottersdorf','Rauental','Förch'],
    umland: 'Baden-Baden, Gaggenau, Bischweier, Muggensturm, Bietigheim und Iffezheim',
    wertstoffhof: 'Wertstoffhof Rastatt (Carl-Theodor-Straße)',
    flavor: 'als Standort vor Ort — wir sitzen in Loffenau bei Rastatt und sind mit der Region tief vertraut',
  },
  'rheinstetten': {
    label: 'Rheinstetten',
    lat: 48.9686, lng: 8.3083,
    plz: '76287',
    districts: ['Forchheim','Mörsch','Neuburgweier','Silberstreifen'],
    umland: 'Karlsruhe, Ettlingen, Au am Rhein, Durmersheim und das südliche Karlsruher Umland',
    wertstoffhof: 'Wertstoffhof Mörsch sowie Wertstoffhöfe Karlsruhe in der Nähe',
    flavor: 'südwestlich von Karlsruhe an der Rheinaue mit überwiegend Einfamilienhaus-Bestand',
  },
  'sinzheim': {
    label: 'Sinzheim',
    lat: 48.7704, lng: 8.1689,
    plz: '76547',
    districts: ['Innenstadt','Halberstung','Kartung','Leiberstung','Müllhofen','Vormberg','Winden','Ebenung'],
    umland: 'Baden-Baden, Bühl, Hügelsheim, Iffezheim und die Ortenau',
    wertstoffhof: 'Wertstoffhof Sinzheim (Industriegebiet)',
    flavor: 'westlich von Baden-Baden in der Rheinebene mit gemischter Wohnbebauung',
  },
  'stutensee': {
    label: 'Stutensee',
    lat: 49.0717, lng: 8.4767,
    plz: '76297',
    districts: ['Blankenloch','Büchig','Friedrichstal','Spöck','Staffort'],
    umland: 'Karlsruhe, Eggenstein-Leopoldshafen, Weingarten, Pfinztal und das nördliche Hardtland',
    wertstoffhof: 'Wertstoffhof Blankenloch sowie die Karlsruher Höfe in Reichweite',
    flavor: 'nördlich von Karlsruhe als ruhige Wohngemeinde mit Einfamilienhäusern und kleinem Gewerbe',
  },
};

export const ALL_TIER1_CITIES = [
  'achern','baden-baden','buehl','ettlingen','gaggenau','gernsbach',
  'karlsruhe','muggensturm','pforzheim','rastatt','rheinstetten','sinzheim','stutensee',
];
